### ISSUE TITLE
Assignment or assertion of equality?

### ISSUE THREAD

**Issue by cclauss** [GoDzM4TT3O/DRC#1]
https://github.com/GoDzM4TT3O/DRC/blob/master/DRC.py#L27

**Comment by cclauss** [comment]
Try running PyFlakes and Check Style under the wrench icon and fix those issues.
![img_2023](https://user-images.githubusercontent.com/3709715/44986776-3042de80-af85-11e8-8f7f-dd7824c86b91.jpeg)

**Comment by GoDzM4TT3O** [comment]
I just did `limit == limit` because I didn’t know what else to type 😬

**Comment by cclauss** [comment]
Understood.  Try changing
```python
if isnum:
	limit == limit
else:
	console.alert("DRC by GoDzM4TT3O", "Please enter a numeric comment limit. For example, if I want to download my last 10 comments this week, I will choose 'week' as comment frequency, and 10 as comment limit.")
# ... to ...
if not isnum:
	limit = console.alert("DRC by GoDzM4TT3O", "Please enter a numeric comment limit. For example, if I want to download my last 10 comments this week, I will choose 'week' as comment frequency, and 10 as comment limit.")
```

**Comment by cclauss** [comment]
Did you try PyFlakes?  Did it help?

**Comment by GoDzM4TT3O** [comment]
Added the code. Also, pyflake says that no issues were found.
