### ISSUE TITLE
Convert Unicode to ASCII -- Maybe not.

### ISSUE THREAD

**Issue by cclauss** [GoDzM4TT3O/DRC#5]
__requests.get(url).text__ will deliver Unicode in both Python 2 and 3.  Perhaps it is better to favor Unicode over favoring ASCII.  All strs are Unicode in Python 3.

**Comment by GoDzM4TT3O** [comment]
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/B679D9E6-0E38-4571-9C3E-1D1AEBF57EAE/Pythonista3/Documents/GoDz/DRC-master/DRC.py", line 60, in <module>
    print("\nAuthor:\n", author, "\n\nComment content:\n", content, "\n\nPermalink:\n", permalink, "\n\nUpvotes:\n", upvotes, "\n\nIs sticky post:\n", issticky, "\nSubreddit:\n", sub, "\n\nPosted on:\nUnix date:\n", unix_date, "\nDate (DD/MM/YYYY):\n", date, "\n\n--------------------\n\n", file=open(outname, "a"))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
